# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero Booking
  description: Hero Booking
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: hero
  form:
    label_date: Date (required)
    label_service: Service (required)
    label_technician: Technician (optional)
    button: SEARCH
    add: Add another
    title: Appointment Information
    select_service:
      - option: Milk and Honey Manicure ($35)
      - option: Cucumber Manicure ($35)
      - option: Lavender Manicure ($35)
      - option: Full set color ($35)
      - option: Ormbre Set ($35)
      - option: Shape ($35)
      - option: Pink and White Fill In ($35)
      - option: Color Powder Full Set ($35)
    select_technician:
      - option: Kim
      - option: Tony

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  form[*].label_date:
    type: text
    label: Label Date
  form[*].label_service:
    type: text
    label: Label Service
  form[*].label_technician:
    type: text
    label: Label Technician
  form[*].button:
    type: text
    label: Text Button
  form[*].add:
    type: text
    label: Text Add
  form[*].title:
    type: text
    label: Title
  form[*].select_service[*].option:
    type: text
    label: Text Option
  form[*].select_technician[*].option:
    type: text
    label: Text Option
