# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero Booking
  description: Hero Booking
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: hero
  form:
    label_date: Date (required)
    label_service: Service (required)
    label_technician: Technician (optional)
    button: SEARCH
    add: Add another
    title: Appointment Information
    confirm:
      title: Confirm booking information ?
      sub_title: We will send a text message to you via the number below after we confirm the calendar for your booking.
      label_name: Your name (required)
      label_phone: Your phone (required)
      label_note: Note (optional)
      note_phone: By entering your number, you agree to receive mobile messages at the phone number provided.
      text_button_cancel: cancel
      text_button_confirm: confirm
    time_morning_appoinment:
      title: Morning
      open_time:
        - time: 10:00 am
        - time: 10:30 am
        - time: 11:00 am
        - time: 11:30 am
    time_afternoon_appoinment:
      title: Afternoon
      open_time:
        - time: 12:00 am
        - time: 12:30 am
        - time: 1:00 am
        - time: 1:30 am
        - time: 2:00 am
        - time: 2:30 am
        - time: 3:00 am
        - time: 3:30 am
        - time: 4:00 am
        - time: 4:30 am
        - time: 5:00 am
        - time: 5:30 am
        - time: 6:00 am
        - time: 6:30 am
        - time: 7:00 am
    select_service:
      - option: Milk and Honey Manicure ($35)
      - option: Cucumber Manicure ($35)
      - option: Lavender Manicure ($35)
      - option: Full set color ($35)
      - option: Ormbre Set ($35)
      - option: Shape ($35)
      - option: Pink and White Fill In ($35)
      - option: Color Powder Full Set ($35)
    select_technician:
      - option: Kim
      - option: Tony

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  form[*].label_date:
    type: text
    label: Label Date
  form[*].label_service:
    type: text
    label: Label Service
  form[*].label_technician:
    type: text
    label: Label Technician
  form[*].button:
    type: text
    label: Text Button
  form[*].add:
    type: text
    label: Text Add
  form[*].title:
    type: text
    label: Title
  form[*].select_service[*].option:
    type: text
    label: Text Option
  form[*].select_technician[*].option:
    type: text
    label: Text Option
  form[*].confirm[*].title:
    type: text
    label: Text Confirm
  form[*].confirm[*].sub_title:
    type: text
    label: Sub Title Confirm
  form[*].confirm[*].label_name:
    type: text
    label: Label Name
  form[*].confirm[*].label_phone:
    type: text
    label: Label Phone
  form[*].confirm[*].label_note:
    type: text
    label: Label Note
  form[*].confirm[*].note_phone:
    type: text
    label: Note Phone
  form[*].confirm[*].text_button_cancel:
    type: text
    label: Text Button Cancel
  form[*].confirm[*].text_button_confirm:
    type: text
    label: Text Button Confirm
  form[*].time_morning_appoinment[*].title:
    type: text
    label: Title Time Morning
  form[*].time_morning_appoinment[*].open_time[*].time:
    type: text
    label: Time Morning
  form[*].time_afternoon_appoinment[*].title:
    type: text
    label: Title Time Afternoon
  form[*].time_afternoon_appoinment[*].open_time[*].time:
    type: text
    label: Time Afternoon
