# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact Section
  description: Contact Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
    id: contact
    title: CONTACT
    google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d50606.958869959104!2d-122.35682973308484!3d37.55659683622224!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808f9e60efa95545%3A0xfd8efcf42dcc1ba7!2sSan%20Mateo%2C%20California%2C%20Hoa%20K%E1%BB%B3!5e0!3m2!1svi!2s!4v1701339468268!5m2!1svi!2s
    background: /images/bg-section7.png  
    icon_star: /images/start.svg
    submit: Submit
    input_name: Enter your name
    input_email: Enter your email
    area_name: Enter your name
    content_form: Have an inquiry or some feedback for us? Fill out the form below to contact our team.
    get_in_touch: Get in Touch
    us: Us 


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  google_map:
    type: text
    label: Google Map
  background:
    type: image
    label: Background
  icon_star:
    type: image
    label: Icon Star
  submit:
    type: text
    label: Submit
  input_name:
    type: text
    label: Input Name
  input_email:
    type: text
    label: Input Email
  area_name:
    type: text
    label: Input Area Name
  content_form:
    type: text
    label: Content 
  get_in_touch:
    type: text
    label: Get In Touch
  us:
    type: text
    label: Us
    

    

