# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Gallery Section
  description: Gallery Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: gallery
  title: OUR GALLERY
  sub_title: Visit our Gallery for more designs.<br/> With our professional, reliable services you will enjoy a unique & relaxing experience.
  gallery_items:
    - img: /images/gallery1.png
      alt_image: Beauty Nails
    - img: /images/gallery1.png
      alt_image: Beauty Nails
    - img: /images/gallery1.png
      alt_image: Beauty Nails
    - img: /images/gallery1.png
      alt_image: Beauty Nails
    - img: /images/gallery1.png
      alt_image: Beauty Nails
    - img: /images/gallery1.png
      alt_image: Beauty Nails
    - img: /images/gallery1.png
      alt_image: Beauty Nails
    - img: /images/gallery1.png
      alt_image: Beauty Nails
    - img: /images/gallery1.png
      alt_image: Beauty Nails
    - img: /images/gallery1.png
      alt_image: Beauty Nails
    - img: /images/gallery1.png
      alt_image: Beauty Nails
    - img: /images/gallery1.png
      alt_image: Beauty Nails

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  sub_title:
    type: markdown
    label: Sub Title
  gallery_items[*].img:
    type: image
    label: Gallery Image
  gallery_items[*].alt_image:
    type: text
    label: Gallery Alt Image
