# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero Section
  description: Hero Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: hero
  banner_slides:
    - banner: /images/banner1.jpeg
      banner_alt: Beauty nail
    - banner: /images/banner2.jpeg
      banner_alt: Beauty nail
    - banner: /images/banner3.jpeg
      banner_alt: Beauty nail
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  banner_slides[*].banner:
    type: image
    label: Banner Image
  banner_slides[*].banner_alt:
    type: text
    label: Alt Image Banner
