# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero Section
  description: Hero Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: hero
  text: The happiest girls always have the prettiest nails
  icon_star: /images/start.svg
  alt_image: Beauty nail
  background: /images/bg-section1.png
  banner_slides:
    - banner: /images/hero1.png
      banner_alt: Beauty nail
    - banner: /images/hero1.png
      banner_alt: Beauty nail
    - banner: /images/hero1.png
      banner_alt: Beauty nail

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  text:
    type: text
    label: Title
  alt_image:
    type: text
    label: Alt Image
  icon_star:
    type: image
    label: Icon Star
  background:
    type: image
    label: Image
  banner_slides[*].banner:
    type: image
    label: Banner
  banner_slides[*].banner_alt:
    type: image
    label: Alt Banner

