# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Testimonial Section
  description: Testimonial Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: testimonial
  title: OUR TESTIMONIAL
  background: /images/bg-testimonial.png
  slide_testimonial:
    - text: Love the quality of service here. Nice atmosphere as far as cleanliness and the decor. Love my tech there named Kim. Great promos throughout the year. Highly suggest the hot stone pedicure treat yourself don’t cheat yourself! Great prices as well
      name: Lauren Davis
      img: /images/testimonial1.png
    - text: Love the quality of service here. Nice atmosphere as far as cleanliness and the decor. Love my tech there named Kim. Great promos throughout the year. Highly suggest the hot stone pedicure treat yourself don’t cheat yourself! Great prices as well
      name: Amy Kelly
      img: /images/testimonial2.png
    - text: Love the quality of service here. Nice atmosphere as far as cleanliness and the decor. Love my tech there named Kim. Great promos throughout the year. Highly suggest the hot stone pedicure treat yourself don’t cheat yourself! Great prices as well
      name: Lauren Davis
      img: /images/testimonial1.png
    - text: Love the quality of service here. Nice atmosphere as far as cleanliness and the decor. Love my tech there named Kim. Great promos throughout the year. Highly suggest the hot stone pedicure treat yourself don’t cheat yourself! Great prices as well
      name: Amy Kelly
      img: /images/testimonial2.png

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  background:
    type: image
    label: Background Image
  slide_testimonial[*].text:
    type: text
    label: Text
  slide_testimonial[*].name:
    type: text
    label: Name
  slide_testimonial[*].img:
    type: image
    label: Image
