# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Service Section
  description: Service Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: services
  title: OUR SERVICE
  sub_title: Professional Nail Care for Ladies and Gentleman
  services:
    - text: Manicure
      img: /images/service1.png
      background_img: /images/bg-service.png
    - text: Manicure
      img: /images/service1.png
      background_img: /images/bg-service.png
    - text: Manicure
      img: /images/service1.png
      background_img: /images/bg-service.png
    - text: Manicure
      img: /images/service1.png
      background_img: /images/bg-service.png
    - text: Manicure
      img: /images/service1.png
      background_img: /images/bg-service.png
    - text: Manicure
      img: /images/service1.png
      background_img: /images/bg-service.png
  welcome:
    img: /images/welcome.jpeg
    img_alt:
    bg_welcome: /images/bg-welcome.png
    title: welcomes to</br>special nails & spa
    title_content1: If you are seeking a nail salon that helps you to rejuvenate your beauty, Special Nails & Spa is the ideal destination! Located conveniently in Houston, TX 77042, our nail salon is proud to deliver the highest quality treatments to our customers.
    title_content2: Our goal is to make each client feel comfortable and memorable! You will always receive the best services and friendly smiles from our talented staff. We offer our clients the best style, quality, and customer service. We invite you to experience the difference in our services.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  sub_title:
    type: text
    label: Sub Title
  services[*].text:
    type: text
    label: Service Text
  services[*].img:
    type: image
    label: Image
  services[*].background_img:
    type: image
    label: Background Image
  welcome[*].img:
    type: image
    label: Image
  welcome[*].bg_welcome:
    type: image
    label: Background Image
  welcome[*].img_alt:
    type: text
    label: Alt Image
  welcome[*].title:
    type: markdown
    label: Title
  welcome[*].title_content1:
    type: text
    label: Title 1
  welcome[*].title_content2:
    type: text
    label: Title 2
