# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero Contact
  description: Hero Contact
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: hero
  title: contact us
  label_name: Your name (required)
  label_email: Your email (required)
  label_subject: Your subject (required)
  label_message: Your message (required)
  text_button: send us
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  label_name:
    type: text
    label: Label Name
  label_email:
    type: text
    label: Label Email
  label_subject:
    type: text
    label: Label Subject
  label_message:
    type: text
    label: Label Message
  text_button:
    type: text
    label: Text Button

