# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero Coupons
  description: Hero Coupons
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: hero
  listImg:
    - img: /images/coupons1.png
      alt: Alt Img
    - img: /images/coupons2.png
      alt: Alt Img
    - img: /images/coupons3.png
      alt: Alt Img
    - img: /images/coupons4.png
      alt: Alt Img
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  listImg[*].img:
    type: image
    label: Image 
  listImg[*].alt:
    type: text
    label: Alt Img 
