# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Nav About
  description: Nav About
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: nav
  sub_title: welcome to <br/>special naiils & spa
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  sub_title:
    type: markdown
    label: Sub Title
